routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['verify' => true]);

Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/verified', 'VerifiedController@index')->name('verified');

Route::group(['middleware' => 'auth'], function() {
    Route::resource('products', 'ProductController');
    Route::resource('tags', 'TagController');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['title'];

    public function product() {
        return $this->belongsToMany(Product::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::paginate(10);
        return view('tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|min:5'
        ]);

        $product = new Tag([
            'title' => $request->get('title')
        ]);

        $product->save();
        
        return redirect('/tags')->with('success', 'The tag has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Tag  $tag)
    {
        return view('tags.show', compact('tag'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag  $tag)
    {
        $request->validate([
            'title' => 'required|string|min:5'
        ]);

        $tag->title = $request->get('title');
        $tag->save();

        return redirect('/tags')->with('success', 'The tag has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        return redirect('/tags')->with('success', 'The item has been deleted');
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('title', 'All Tags')


@section('content')
<div class="row">
    <div class="col-lg-6 mx-auto">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

        <form method="POST" action="{{ route('tags.store') }}">
            @csrf
                <div class="form-group">
                    <label for="tag-title">Title</label>
                    <input type="text" name='title' value=" {{ old('title') }}" class="form-control" id='tag-title'>
                </div>
            <button type="submite" class="btn btn-success">Add Tag</button>
        </form>
    </div>
</div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Tag ' . $tag->id)


@section('content')
<div class="row">
    <div class="col-lg-6 mx-auto">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

        <form method="POST" action="{{ route('tags.update', $tag) }}">
            @csrf
            @method('PATCH')
                <div class="form-group">
                    <label for="tag-title">Title</label>
                    <input type="text" name='title' value=" {{ $tag->title }}" class="form-control" id='tag-title'>
                </div>
                <button type="submite" class="btn btn-success">Update tag</button>
        </form>
    </div>
</div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('title', 'All Tags')


@section('content')

<a href="{{ route('tags.create') }}" class="btn btn-success">Create Tag</a>

@if (session()->get('success'))
	<div class="alert alert-success mt-3">
		{{ session()->get('success') }}
	</div>
@endif

<table class="table table-striped mt-3">
	<thead>
	  <tr>
		<th scope="col">#</th>
		<th scope="col">Title</th>
		<th scope="col">Url</th>
		<th></th>
	  </tr>
	</thead>
	<tbody>
		@foreach ($tags as $tag)
	 	<tr>
			<th scope="row">{{ $tag->id }}</th>
			<td>{{ $tag->title }}</td>
			<td>{{ $tag->url }}</td>
			<td class="table-buttons">
				<a href="{{ route('tags.show', $tag) }}" class="btn btn-success">
					<i class="material-icons">visibility</i>
				</a>
				<a href="{{ route('tags.edit', $tag) }}" class="btn btn-primary">
					<i class="material-icons">edit</i>
				</a>
				<form method="POST" action="{{ route('tags.destroy', $tag) }}">
					@csrf
					@method('DELETE')
					<button type="submit" class="btn btn-danger">
						<i class="material-icons">delete</i>
					</button>
				</form>
	 		</td>
	 	</tr>
	  @endforeach
	  </tr>
	</tbody>
  </table>

  {{ $tags->links()}}
  
@endsection

resources/views/tags/show.blade.php
@extends('layouts.app')

@section('title', 'Show Tag ' . $tag->id)


@section('content')

<div class="card">
    <div class="card-body">
      <h3>{{ $tag->title }}</h3>
    </div>
  </div>

@endsection